ffosh: ffosh.cpp cmdParser.cpp envVar.cpp changeDir.cpp argvManager.cpp
	g++ -o ffosh -Wall -Werror -std=gnu++03 -pedantic -ggdb3 ffosh.cpp cmdParser.cpp envVar.cpp changeDir.cpp argvManager.cpp
clean:
	rm -f *~
